"""
recon-scheduler Q6 harness: what does a sample-based 8-piece kit cost to load and
trigger, versus a synthesized piece? Real Chrome, real decodeAudioData on real WAV
bytes (kit_samples/, generated by gen_kit_wavs.py), served over http so fetch() works
(file:// blocks fetch by CORS in Chrome).
"""
import json, http.server, threading, socketserver, os
from playwright.sync_api import sync_playwright

SCRATCH_DIR = os.path.dirname(__file__)
CHROME_PATH = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

def main():
    handler = http.server.SimpleHTTPRequestHandler
    os.chdir(SCRATCH_DIR)
    httpd = socketserver.TCPServer(("127.0.0.1", 8891), handler)
    t = threading.Thread(target=httpd.serve_forever, daemon=True)
    t.start()

    fileNames = [
        "01_kick.wav","02_snare.wav","03_hihat_closed.wav","04_hihat_open.wav",
        "05_clap.wav","06_tom_low.wav","07_tom_high.wav","08_rim.wav",
    ]

    results = {}
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(executable_path=CHROME_PATH, headless=True)
            page = browser.new_page()
            page.goto("http://127.0.0.1:8891/harness_q6_page.html")
            decode_result = page.evaluate(f"window.__decodeAll({json.dumps(fileNames)})")
            results["decode"] = decode_result
            print("Decode results:")
            for r in decode_result["perFile"]:
                print(" ", r)
            print("Total decode ms for 8 files:", decode_result["totalDecodeMs"])

            trigger_result = page.evaluate("window.__triggerCost(500)")
            results["sample_trigger_cost"] = trigger_result
            print("Sample trigger cost (500 triggers):", trigger_result)

            synth_result = page.evaluate("window.__synthTriggerCost(500)")
            results["synth_trigger_cost"] = synth_result
            print("Synth trigger cost (500 triggers):", synth_result)

            browser.close()
    finally:
        httpd.shutdown()

    total_mem = sum(r["decodedMemoryBytes"] for r in results["decode"]["perFile"])
    total_disk = sum(r["bytesOnDisk"] for r in results["decode"]["perFile"])
    results["summary"] = {
        "total_bytes_on_disk_8_files": total_disk,
        "total_decoded_memory_bytes_8_files": total_mem,
        "memory_expansion_ratio": round(total_mem/total_disk, 2),
    }
    print("Summary:", results["summary"])

    out = os.path.join(SCRATCH_DIR, "results_q6_kit_cost.json")
    with open(out, "w") as f:
        json.dump(results, f, indent=2)
    print("Wrote", out)

if __name__ == "__main__":
    main()
